export const mockData = [
  { id: 'Block 1', parents: [] },
  { id: 'Block 2', parents: ['Block 1'] },
  { id: 'Block 3', parents: ['Block 1'] },
  { id: 'Block 4', parents: ['Block 2', 'Block 3'] },
  { id: 'Block 5', parents: ['Block 2'] },
  { id: 'Block 6', parents: ['Block 3'] },
  { id: 'Block 7', parents: ['Block 4', 'Block 5'] },
  { id: 'Block 8', parents: ['Block 5', 'Block 6'] },
  { id: 'Block 9', parents: ['Block 7', 'Block 8'] },
  { id: 'Block 10', parents: ['Block 8', 'Block 9'] },
  { id: 'Block 11', parents: ['Block 7'] },
  { id: 'Block 12', parents: ['Block 10', 'Block 11'] },
  { id: 'Block 13', parents: ['Block 11'] },
  { id: 'Block 14', parents: ['Block 12', 'Block 13'] },
  { id: 'Block 15', parents: ['Block 12'] },
  { id: 'Block 16', parents: ['Block 14', 'Block 15'] },
  { id: 'Block 17', parents: ['Block 13', 'Block 16'] },
  { id: 'Block 18', parents: ['Block 17', 'Block 15'] },
  { id: 'Block 19', parents: ['Block 16', 'Block 18'] },
  { id: 'Block 20', parents: ['Block 18'] },
  { id: 'Block 21', parents: ['Block 20', 'Block 17'] },
  { id: 'Block 22', parents: ['Block 19', 'Block 21'] },
  { id: 'Block 23', parents: ['Block 22'] },
  { id: 'Block 24', parents: ['Block 22', 'Block 23'] },
  { id: 'Block 25', parents: ['Block 24', 'Block 21'] },
  { id: 'Block 26', parents: ['Block 23', 'Block 25'] },
  { id: 'Block 27', parents: ['Block 26'] },
  { id: 'Block 28', parents: ['Block 25', 'Block 27'] },
  { id: 'Block 29', parents: ['Block 28'] },
  { id: 'Block 30', parents: ['Block 28', 'Block 29'] },
  { id: 'Block 31', parents: ['Block 30'] },
  { id: 'Block 32', parents: ['Block 29', 'Block 31'] },
  { id: 'Block 33', parents: ['Block 31', 'Block 32'] },
  { id: 'Block 34', parents: ['Block 30', 'Block 33'] },
  { id: 'Block 35', parents: ['Block 34', 'Block 33'] },
  { id: 'Block 36', parents: ['Block 34', 'Block 35'] },
  { id: 'Block 37', parents: ['Block 35', 'Block 36'] },
  { id: 'Block 38', parents: ['Block 37', 'Block 32'] },
  { id: 'Block 39', parents: ['Block 38', 'Block 36'] },
  { id: 'Block 40', parents: ['Block 37', 'Block 39'] },
  { id: 'Block 41', parents: ['Block 40'] },
  { id: 'Block 42', parents: ['Block 40', 'Block 41'] },
  { id: 'Block 43', parents: ['Block 41', 'Block 42'] },
  { id: 'Block 44', parents: ['Block 42'] },
  { id: 'Block 45', parents: ['Block 43', 'Block 44'] },
  { id: 'Block 46', parents: ['Block 45', 'Block 44'] },
  { id: 'Block 47', parents: ['Block 46', 'Block 45'] },
  { id: 'Block 48', parents: ['Block 47', 'Block 46'] },
  { id: 'Block 49', parents: ['Block 48', 'Block 44'] },
  { id: 'Block 50', parents: ['Block 49', 'Block 47'] },
  { id: 'Block 51', parents: ['Block 50'] },
  { id: 'Block 52', parents: ['Block 51', 'Block 50'] },
  { id: 'Block 53', parents: ['Block 52', 'Block 48'] },
  { id: 'Block 54', parents: ['Block 53', 'Block 49'] },
  { id: 'Block 55', parents: ['Block 54'] },
  { id: 'Block 56', parents: ['Block 54', 'Block 55'] },
  { id: 'Block 57', parents: ['Block 56', 'Block 53'] },
  { id: 'Block 58', parents: ['Block 57', 'Block 56'] },
  { id: 'Block 59', parents: ['Block 58'] },
  { id: 'Block 60', parents: ['Block 59'] },
];
