export const mockData = [
  { id: 'Block 1', isChain: true, blueparents: [] },
  { id: 'Block 2', isChain: true, blueparents: ['Block 1'] },
  { id: 'Block 3', isChain: true, blueparents: ['Block 1'] },
  { id: 'Block 4', isChain: true, blueparents: ['Block 2', 'Block 3'] },
  { id: 'Block 5', isChain: true, blueparents: ['Block 2'] },
  { id: 'Block 6', isChain: true, blueparents: ['Block 3'] },
  { id: 'Block 7', isChain: true, blueparents: ['Block 4', 'Block 5'] },
  { id: 'Block 8', isChain: true, blueparents: ['Block 5', 'Block 6'] },
  { id: 'Block 9', isChain: true, blueparents: ['Block 7', 'Block 8'] },
  { id: 'Block 10', isChain: true, blueparents: ['Block 8', 'Block 9'] },
  { id: 'Block 11', isChain: true, blueparents: ['Block 7'] },
  { id: 'Block 12', isChain: true, blueparents: ['Block 10', 'Block 11'] },
  { id: 'Block 13', isChain: true, blueparents: ['Block 11'] },
  { id: 'Block 14', isChain: true, blueparents: ['Block 12', 'Block 13'] },
  { id: 'Block 15', isChain: true, blueparents: ['Block 12'] },
  { id: 'Block 16', isChain: true, blueparents: ['Block 14', 'Block 15'] },
  { id: 'Block 17', isChain: true, blueparents: ['Block 13', 'Block 16'] },
  { id: 'Block 18', isChain: true, blueparents: ['Block 17', 'Block 15'] },
  { id: 'Block 19', isChain: true, blueparents: ['Block 16', 'Block 18'] },
  { id: 'Block 20', isChain: true, blueparents: ['Block 18'] },
  { id: 'Block 21', isChain: true, blueparents: ['Block 20', 'Block 17'] },
  { id: 'Block 22', isChain: true, blueparents: ['Block 19', 'Block 21'] },
  { id: 'Block 23', isChain: true, blueparents: ['Block 22'] },
  { id: 'Block 24', isChain: true, blueparents: ['Block 22', 'Block 23'] },
  { id: 'Block 25', isChain: true, blueparents: ['Block 24', 'Block 21'] },
  { id: 'Block 26', isChain: true, blueparents: ['Block 23', 'Block 25'] },
  { id: 'Block 27', isChain: true, blueparents: ['Block 26'] },
  { id: 'Block 28', isChain: true, blueparents: ['Block 25', 'Block 27'] },
  { id: 'Block 29', isChain: true, blueparents: ['Block 28'] },
  { id: 'Block 30', isChain: true, blueparents: ['Block 28', 'Block 29'] },
  { id: 'Block 31', isChain: true, blueparents: ['Block 30'] },
  { id: 'Block 32', isChain: true, blueparents: ['Block 29', 'Block 31'] },
  { id: 'Block 33', isChain: true, blueparents: ['Block 31', 'Block 32'] },
  { id: 'Block 34', isChain: true, blueparents: ['Block 30', 'Block 33'] },
  { id: 'Block 35', isChain: true, blueparents: ['Block 34', 'Block 33'] },
  { id: 'Block 36', isChain: true, blueparents: ['Block 34', 'Block 35'] },
  { id: 'Block 37', isChain: true, blueparents: ['Block 35', 'Block 36'] },
  { id: 'Block 38', isChain: true, blueparents: ['Block 37', 'Block 32'] },
  { id: 'Block 39', isChain: true, blueparents: ['Block 38', 'Block 36'] },
  { id: 'Block 40', isChain: true, blueparents: ['Block 37', 'Block 39'] },
  { id: 'Block 41', isChain: true, blueparents: ['Block 40'] },
  { id: 'Block 42', isChain: true, blueparents: ['Block 40', 'Block 41'] },
  { id: 'Block 43', isChain: true, blueparents: ['Block 41', 'Block 42'] },
  { id: 'Block 44', isChain: true, blueparents: ['Block 42'] },
  { id: 'Block 45', isChain: true, blueparents: ['Block 43', 'Block 44'] },
  { id: 'Block 46', isChain: true, blueparents: ['Block 45', 'Block 44'] },
  { id: 'Block 47', isChain: true, blueparents: ['Block 46', 'Block 45'] },
  { id: 'Block 48', isChain: true, blueparents: ['Block 47', 'Block 46'] },
  { id: 'Block 49', isChain: true, blueparents: ['Block 48', 'Block 44'] },
  { id: 'Block 50', isChain: true, blueparents: ['Block 49', 'Block 47'] },
  { id: 'Block 51', isChain: true, blueparents: ['Block 50'] },
  { id: 'Block 52', isChain: true, blueparents: ['Block 51', 'Block 50'] },
  { id: 'Block 53', isChain: true, blueparents: ['Block 52', 'Block 48'] },
  { id: 'Block 54', isChain: true, blueparents: ['Block 53', 'Block 49'] },
  { id: 'Block 55', isChain: true, blueparents: ['Block 54'] },
  { id: 'Block 56', isChain: true, blueparents: ['Block 54', 'Block 55'] },
  { id: 'Block 57', isChain: true, blueparents: ['Block 56', 'Block 53'] },
  { id: 'Block 58', isChain: true, blueparents: ['Block 57', 'Block 56'] },
  { id: 'Block 59', isChain: true, blueparents: ['Block 58'] },
  { id: 'Block 60', isChain: true, blueparents: ['Block 59'] },
];
